### ISSUE TITLE
Quickstart fails with jboss-eap-6.2

### ISSUE THREAD

**Issue by imrankhurram** [jboss-developer/jboss-eap-quickstarts#1003]
mvn clean install jboss-as:deploy fails:

[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountere
d while processing the POMs:
[ERROR] Non-resolvable import POM: Failure to find org.jboss.as:jboss-as-ejb-cli
ent-bom:pom:7.3.0.Final-redhat-14 in http://repo.maven.apache.org/maven2 was cac
hed in the local repository, resolution will not be reattempted until the update
 interval of central has elapsed or updates are forced @ org.jboss.quickstarts.e
ap:jboss-cluster-ha-singleton:6.2.0.GA, D:\work\jboss-eap-quickstarts-6.2.0.GA\c
luster-ha-singleton\pom.xml, line 85, column 25
[ERROR] 'dependencies.dependency.version' for org.jboss.msc:jboss-msc:jar is mis
sing. @ org.jboss.quickstarts.eap:jboss-cluster-ha-singleton-service:[unknown-ve
rsion], D:\work\jboss-eap-quickstarts-6.2.0.GA\cluster-ha-singleton\service\pom.
xml, line 45, column 21
[ERROR] 'dependencies.dependency.version' for org.jboss.as:jboss-as-clustering-s
ingleton:jar is missing. @ org.jboss.quickstarts.eap:jboss-cluster-ha-singleton-
service:[unknown-version], D:\work\jboss-eap-quickstarts-6.2.0.GA\cluster-ha-sin
gleton\service\pom.xml, line 63, column 21

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBu
ilder.java:405)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:663)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven
.java:654)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:243)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
[ERROR]
[ERROR]   The project org.jboss.quickstarts.eap:jboss-cluster-ha-singleton-servi
ce:6.2.0.GA (D:\work\jboss-eap-quickstarts-6.2.0.GA\cluster-ha-singleton\service
\pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.as:jboss-as-ejb
-client-bom:pom:7.3.0.Final-redhat-14 in http://repo.maven.apache.org/maven2 was
 cached in the local repository, resolution will not be reattempted until the up
date interval of central has elapsed or updates are forced @ org.jboss.quickstar
ts.eap:jboss-cluster-ha-singleton:6.2.0.GA, D:\work\jboss-eap-quickstarts-6.2.0.
GA\cluster-ha-singleton\pom.xml, line 85, column 25 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Failure to find or
g.jboss.as:jboss-as-ejb-client-bom:pom:7.3.0.Final-redhat-14 in http://repo.mave
n.apache.org/maven2 was cached in the local repository, resolution will not be r
eattempted until the update interval of central has elapsed or updates are force
d
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectMod
elResolver.java:175)
        at org.apache.maven.model.building.DefaultModelBuilder.importDependencyM
anagement(DefaultModelBuilder.java:1076)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultMode
lBuilder.java:427)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultMode
lBuilder.java:398)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBu
ilder.java:602)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBu
ilder.java:394)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:663)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven
.java:654)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:243)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to
 find org.jboss.as:jboss-as-ejb-client-bom:pom:7.3.0.Final-redhat-14 in http://r
epo.maven.apache.org/maven2 was cached in the local repository, resolution will
not be reattempted until the update interval of central has elapsed or updates a
re forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(Defa
ultArtifactResolver.java:459)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtif
acts(DefaultArtifactResolver.java:262)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtif
act(DefaultArtifactResolver.java:239)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtif
act(DefaultRepositorySystem.java:295)
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectMod
elResolver.java:171)
        ... 20 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to fin
d org.jboss.as:jboss-as-ejb-client-bom:pom:7.3.0.Final-redhat-14 in http://repo.
maven.apache.org/maven2 was cached in the local repository, resolution will not
be reattempted until the update interval of central has elapsed or updates are f
orced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newExcepti
on(DefaultUpdateCheckManager.java:232)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtif
act(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownlo
ads(DefaultArtifactResolver.java:599)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownl
oads(DefaultArtifactResolver.java:518)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(Defa
ultArtifactResolver.java:436)
        ... 24 more
[ERROR]     'dependencies.dependency.version' for org.jboss.msc:jboss-msc:jar is
 missing. @ org.jboss.quickstarts.eap:jboss-cluster-ha-singleton-service:[unknow
n-version], D:\work\jboss-eap-quickstarts-6.2.0.GA\cluster-ha-singleton\service\
pom.xml, line 45, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.as:jboss-as-clusteri
ng-singleton:jar is missing. @ org.jboss.quickstarts.eap:jboss-cluster-ha-single
ton-service:[unknown-version], D:\work\jboss-eap-quickstarts-6.2.0.GA\cluster-ha
-singleton\service\pom.xml, line 63, column 21
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException

**Comment by sgilda** [comment]
Since there has been no response, I am closing this issue. Feel free to reopen it if you are still experiencing problems.
